### ISSUE TITLE
74LS189

### ISSUE THREAD

**Issue by loneregister** [DutchMaker/8-bit-Breadboard-Computer#1]
What / where can one find the DIP style memory packages that lend themselves to breadboards?
74LS200 or other of the 74 series ram chips would be fine - I just cannot seem to locate parts.

**Comment by DutchMaker** [comment]
I found them on eBay: http://www.ebay.com/itm/381034057645
This is exactly the listing that I purchased, so you can be sure it's the right one.

**Comment by loneregister** [comment]
Thanks DutchMaker.  Just ordered all the parts, and am going to be building this up with my son.
Then, I think I'll work on xferring this to a full 6809E build to emulate/reproduce a Tandy Color Computer - maybe.  LOL

**Comment by DutchMaker** [comment]
Glad I could help.
Good luck with the project!
Sounds like some quality father/son time! :)
