### ISSUE TITLE
Kinda new to this

### ISSUE THREAD

**Issue by loneregister** [DutchMaker/8-bit-Breadboard-Computer#2]
Hi Guys,

I am kinda new to this - but just spent a few hours with my son doing the clock circuit breadboard.
We only had the 74LS00 and 74LS04, so we had to design our own logic circuit.  I mocked it up and PDF'd it, and would love to add to the git here.

I forked it over to my git account, and did so - but have no idea how to provide that information over to you?

Kevin

**Comment by DotTech** [comment]
Seems you figured it out already, it is done using a Pull Request.
I will take a look at it when I have some time for it and add it in my repository.
Thanks for sharing!

Will have to figure out a way of incorporating alternative circuits in the parts list as Ben himself is also doing some alternatives in his videos (his latest Output Register is different from the other registers)
