### ISSUE TITLE
Wrong demultiplexer listed

### ISSUE THREAD

**Issue by v4nz666** [DutchMaker/8-bit-Breadboard-Computer#5]
In the control module parts list (and the output module parts list, I believe), you've got a 74LS139 (Dual 2-to-4 line decoder) listed, however, Ben uses 74LS138s (3-to-8 line decoder).

**Comment by DutchMaker** [comment]
You are right, I put the wrong part in the list.
It has been fixed now.
Thanks for letting me know!
