### ISSUE TITLE
74LS173 Datasheet link is broken

### ISSUE THREAD

**Issue by JanGross** [DutchMaker/8-bit-Breadboard-Computer#6]
The Datasheet for the 74LS173 (4-bit D-type register) can no longer be found at TIs site, at least not at the current URL.
However, there is a datasheet that seems correct at this URL:  http://www.ti.com/lit/ds/symlink/sn74ls173a.pdf

**Comment by DutchMaker** [comment]
Thanks for letting me know @JanGross 
I updated the links.
